
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<ApplicationIcon>Assets\icon.ico</ApplicationIcon>
	</PropertyGroup>

	<PropertyGroup>
		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\icon.ico" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
		<PackageReference Include="LiveMarkdown.Avalonia.Math" Version="2.4.3" />
		<PackageReference Include="LiveMarkdown.Avalonia.Mermaid" Version="2.4.3" />
		<PackageReference Include="Tmds.DBus.Protocol" Version="0.94.2" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
		<PackageReference Include="NAudio" Version="2.3.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
		<PackageReference Include="Porta.Pty" Version="1.0.7" />
		<PackageReference Include="Unicode.net" Version="2.0.0" />
		<PackageReference Include="Wcwidth" Version="4.0.1" />
		<PackageReference Include="WebReaper.Cdp" Version="11.3.1" />
		<PackageReference Include="WebReaper.Playwright" Version="11.3.1" />
		<PackageReference Include="WebReaper.Stealth.CloakBrowser" Version="11.3.1" />
		<PackageReference Include="XTerm.NET" Version="1.0.12" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LLMDesktopAssistant.Blazor\LLMDesktopAssistant.Blazor.csproj" />
		<ProjectReference Include="..\LLMDesktopAssistant\LLMDesktopAssistant.csproj" />
	</ItemGroup>
	
	<Target Name="PublishBlazorStaticAssets" BeforeTargets="BeforeBuild">
		<Exec Command="dotnet publish &quot;..\LLMDesktopAssistant.Blazor\LLMDesktopAssistant.Blazor.csproj&quot; -c $(Configuration) -o &quot;$(TargetDir)&quot;" />
	</Target>
	
</Project>
